markdown: kramdown
highlighter: rouge
permalink: /:categories/:title.html 
excerpt_separator: "<!-- more -->"

github: hosocongty
author: "hosocongty"
email: info@hosocongty.xyz
name: "Panxw's Blog"
baseurl: /
url: http://hosocongty.xyz
domain: hosocongty.xyz

all_categories: [
  ["android", "Android开发","/android/index.html"], 
  ["react", "React Native", "/react/index.html"],
  ["web", "Web建站","/web/index.html"], 
  ["linux", "Linux相关","/linux/index.html"],
  ["git", "git用法","/git/index.html"],
  ["program", "软件开发","/program/index.html"],
  ["vps", "VPS","/vps/index.html"],
  ["other", "杂记","/other/index.html"],
  ["read", "书摘","/read/index.html"], 
  ["about", "关于","/about.html"]
]

paginate: 10 
paginate_path: "index_:num"

index_layout: "index.html"
category_layout: "_layouts/category.html"
tag_layout: "_layouts/tag.html"

gems: [jekyll-paginate]

collections:
  docs:
    output: true

copyright: []
#timezone: Asia/Hanoi
