markdown: kramdown
highlighter: rouge
permalink: /:categories/:title.html 
excerpt_separator: "<!-- more -->"

github: hosocongty
author: "hosocongty"
email: info@hosocongty.xyz
name: "hosocongty's Blog"
baseurl: /
url: http://hosocongty.xyz
domain: hosocongty.xyz

all_categories: [
  ["Read", "Read","/web/index.html"], 
  ["About", "About","/about.html"],
  ["User Agreement", "User Agreement","/User-Agreement.html"], 
  ["Privacy Policy", "Privacy Policy","/Privacy-Policy.html"]
]

paginate: 10 
paginate_path: "index_:num"

index_layout: "index.html"
category_layout: "_layouts/category.html"
tag_layout: "_layouts/tag.html"

gems: [jekyll-paginate]

collections:
  docs:
    output: true

copyright: []
#timezone: Asia/Hanoi
